### ISSUE TITLE
Corrección: Kitten

### ISSUE THREAD

**Issue by ghost** [Clau1889/kitten-reto-codigo#1]
A mejorar: No olvides hacer la configuracion del box-sizing para el body, porque si no se hace, se genera este espacio en blanco en los bordes del navegador que finalmente provoca un scroll no deseado. Prueba mejorando tu css con estas propiedades 
```css
body{   
  box-sizing:border-box;
  padding:0;
  margin:0;
}
```
Puntuacion: **196.40/200**
